static:
  logger:
    version: 1
    formatters:
      standard:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    handlers:
      console:
        level: "DEBUG"
        formatter: standard
        class: logging.StreamHandler
        stream: ext://sys.stdout
      file_full:
        level: "DEBUG"
        formatter: standard
        class: logging.handlers.WatchedFileHandler
        filename: "./logs/full.log"
      file_error:
        level: "ERROR"
        formatter: standard
        class: logging.handlers.WatchedFileHandler
        filename: "./logs/error.log"
    loggers:
      root:
        level: "DEBUG"
        handlers:
          - console
          - file_error
      "PluginStore":
        level: "ERROR"
        handlers:
          - console
          - file_full
          - file_error
      "Dispatcher":
        level: "DEBUG"
        handlers:
          - console
          - file_full
          - file_error

dynamic:
  plugins:
    uploaded:
      - "system.converter"
      - "system.storage"
      - "system.fastapi"
      - "amocrm.amoclient"
      - "amocrm.functions"
      - "amocrm.records.provider"
      - "amocrm.widget.asterisk"
      - "amocrm.widget.asterisk_ng"
      - "telephony.ami_manager"
      - "telephony.asterisk16.reflector"
      - "telephony.asterisk16.functions"
      - "standard.domain"
      - "telephony.redirecting"
      - "telephony.records_provider"

    plugins_settings:
      "standard.domain":
        agents:
          "alexander.filippov@iqtek.ru": 613
          "kirill.martynenko@iqtek.ru": 610

      "amocrm.amoclient":
        backup_file_path: "./credentials.txt"
        encryption_key: "asterisk_ng"
        integration_id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        secret_key: "secret_key",
        auth_code: "auth_code",
        base_url: "https://mycompany.amocrm.ru/",
        redirect_uri: "https://mycompany.ru/",

      "amocrm.functions":
        pipeline: "Воронка"
        source: "AsteriskNG"
        source_uid: "AsteriskNG"
        source_name: "AsteriskNG"
        service_code: "AsteriskNG"

      "amocrm.records.provider":
        base_url: https://webhook.api.ru/records
        enable_conversion: true

      "amocrm.widget.asterisk":
        login: "login"
        password: "password"

      "amocrm.widget.asterisk_ng":
        secret_key: "AsteriskNG"

      "telephony.ami_manager":
        user: admin
        host: 127.0.0.1
        port: 5038
        secret: secret

      "telephony.asterisk16.functions":
        origination_contex: from-internal
        origination_timeout: 30000
        redirect_contex: from-internal

      "telephony.records_provider":
        mysql:
          host: 127.0.0.1
          port: 3306
          user: user
          password: password
          database: asteriskcdrdb
        media_root: "/var/spool/asterisk/monitor/%Y/%m/%d/"

      "system.storage":
        host: 127.0.0.1
        port: 6379
        database: 0

      "system.fastapi":
        host: 0.0.0.0
        port: 8000

      "system.converter":
        tmp_dir: ./tmp
