from .GetCallDirectionFunctionImpl import GetCallDirectionFunctionImpl
from .IsInternalNumberFunctionImpl import IsInternalNumberFunctionImpl
from .OriginationRequestCommandImpl import OriginationRequestCommandImpl
