from .HangupMethod import HangupMethod
from .OriginationMethod import OriginationMethod
from .PingMethod import PingMethod
from .RedirectMethod import RedirectMethod
from .SetHoldMethod import SetHoldMethod
from .SetMuteMethod import SetMuteMethod
from .GetAgentStatusMethod import GetAgentStatusMethod
from .GetLastContactsMethod import GetLastContactsMethod
from .GetContactsMethod import GetContactsMethod
from .OriginationByContactMethod import OriginationByContactMethod
