scenario: classic
scenario_configs_dir: ./configs

telephony:
  type: asterisk_16
  settings:
    storage_prefix: telephony
    ami:
      host: 127.0.0.1
      port: 5038
      user: user
      secret: secret
    cdr:
      mysql:
        host: 127.0.0.1
        port: 3306
        user: user
        password: password
        database: asteriskcdrdb
      media_root: "/var/spool/asterisk/monitor/%Y/%m/%d/"
    dial:
      context: from-internal
      timeout: 30000

crm:
  type: amocrm
  settings:
    storage_prefix: crm
    kernel:
      call_logging:
        enable_conversion: true
        tmp_directory: "./files"
        base_url: https://webhook.iqtek.ru/

      integration:
        integration_id: xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx
        secret_key: secret_key
        auth_code: auth_code
        redirect_uri: https://mycompany.ru/
        base_url: https://mycompany.amocrm.ru/

    widget:
      type: asterisk_widget
      settings:
        login: login
        password: password
        users:
          111: my_email@email.ru
          222: someone_mail@email.ru
          333: other_mail@email.ru


infrastructure:

  integration:
    host: 0.0.0.0
    port: 8000

  message_bus:
    type: rabbitmq
    settings:
      rabbitmq:
        host: 127.0.0.1
        port: 5672
        login: guest
        password: guest
        virtualhost: '/'
        ssl: false
        login_method: PLAIN
      exchange_name: asterisk_amocrm_ng_exchange
      exchange_type: direct
      queue_name: asterisk_amocrm_ng
      routing_key: asterisk_amocrm_ng


  event_bus:
    type: extended
    settings:
      workers: 1

  storage:
    type: redis
    settings:
      host: 127.0.0.1
      port: 6379
      database: 1

  logger:
    version: 1
    formatters:
      standard:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    handlers:
      console:
        level: "DEBUG"
        formatter: standard
        class: logging.StreamHandler
        stream: ext://sys.stdout
      file_full:
        level: "DEBUG"
        formatter: standard
        class: logging.handlers.WatchedFileHandler
        filename: "./full.log"
      file_error:
        level: "ERROR"
        formatter: standard
        class: logging.handlers.WatchedFileHandler
        filename: "./error.log"
    logger:
      root:
        level: "DEBUG"
        handlers:
          - console
          - file_full
          - file_error

      "panoramisk.manager":
        level: "ERROR"
        handlers:
          - console
          - file_error
